### ISSUE TITLE
Max brightness issue

### ISSUE THREAD

**Issue by sumanchapai** [LutherAstrophysics/m23#24]
@minhviet0308, we might have to rethink about this.
Are any values from the new camera above > 65000? 
Can they theoretically be? What's the datatype of the new 
camera image matrix?
https://github.com/LutherAstrophysics/m23/blob/3e0a3f140f8a5698bb2a3dca6f9679fa8b2e0892/m23/calibrate/calibration.py#L94-L101
https://github.com/LutherAstrophysics/m23/blob/3e0a3f140f8a5698bb2a3dca6f9679fa8b2e0892/m23/constants.py#L3

**Comment by minhviet0308** [comment]
@sumanchapai 
The maximum brightness that a pixel can be is 2^16. For all of our stars, the max brightness falls within 40000-50000, which is well under this threshold. You can verify this by seeing the first star, which is the brightest, in our log files combined. 
The datatype of the new camera image matrix is 2056x2048x16 originally.

**Comment by minhviet0308** [comment]
@sumanchapai 
The maximum brightness that a pixel can be is 2^16. For all of our stars, the max brightness falls within 40000-50000, which is well under this threshold. You can verify this by seeing the first star, which is the brightest, in our log files combined. 

The datatype of the new camera image matrix is 2056x2048x16 originally.
